INSERT INTO users (username,           email) VALUES ('Vít Baisa',                             'vit.baisa@gmail.com');
INSERT INTO users (username,           email) VALUES ('Jan Vodák',                             'jan@vodak.net');
INSERT INTO users (username,           email) VALUES ('Zdeněk Mejzlík',                        'ZMejzlik@seznam.cz');
INSERT INTO users (username, nickname, email) VALUES ('Hana Pospíšilová', 'Hanka Pospíšilová', 'hana.pospisilova@stottan.com');
INSERT INTO users (username, nickname, email) VALUES ('Martin Svoboda',   'Máca',              'macasv@seznam.cz');

--INSERT INTO users (username, email) VALUES ('Alena Königová', 'konik123@seznam.cz');
--INSERT INTO users (username, email) VALUES ('Barbora Důbravová', 'barunka.dubravova@seznam.cz');
--INSERT INTO users (username, email) VALUES ('Barbora Mikšátková', 'barbora.miks@gmail.com');
--INSERT INTO users (username, email) VALUES ('Dariusz Nahrebecki', 'peroton@yahoo.de');
--INSERT INTO users (username, email) VALUES ('David Tran', 'tranquoctrung@seznam.cz');
--INSERT INTO users (username, email) VALUES ('Doubravka Brávková', 'doubravka.bravkova@gmail.com');
--INSERT INTO users (username, email) VALUES ('Dušan Nechvátal', 'dunech66@gmail.com');
--INSERT INTO users (username, email) VALUES ('Elisabeth Stavělová', 'stavelovae@seznam.cz');
--INSERT INTO users (username, email) VALUES ('Hana Nechvátalová', 'hanech@seznam.cz');
--INSERT INTO users (username, email) VALUES ('Irena Blažková', 'IrisBlazkova@seznam.cz');
--INSERT INTO users (username, email) VALUES ('Jan Lošťák', 'lostak.jan@seznam.cz');
--INSERT INTO users (username, email) VALUES ('Jan Vodák', 'jan@vodak.net');
--INSERT INTO users (username, email) VALUES ('Jana Havlová', 'janca.havlova@gmail.com');
--INSERT INTO users (username, email) VALUES ('Jindřich Řepka', 'jindrich@repka.cz');
--INSERT INTO users (username, email) VALUES ('Jiří Tran', 'bach.tran@seznam.cz');
--INSERT INTO users (username, email) VALUES ('Klára Svobodová', 'klarassvobodova@gmail.com');
--INSERT INTO users (username, email) VALUES ('Lisa Šplíchalová', 'lisasplichalova@gmail.com');
--INSERT INTO users (username, email) VALUES ('Lucie Smolová', 'smolova03@gmail.com');
--INSERT INTO users (username, email) VALUES ('Marek Čupa', 'maracupa@gmail.com');
--INSERT INTO users (username, email) VALUES ('Marián Blažek', 'blazek@malbypokoju.cz');
--INSERT INTO users (username, email) VALUES ('Marián König', 'konig@seznam.cz');
--INSERT INTO users (username, email) VALUES ('Martin Nguyen', 'nguyenkhactuan86@gmail.com');
--INSERT INTO users (username, email) VALUES ('Martin Sokol', 'm.sokol@tiscali.cz');
--INSERT INTO users (username, email) VALUES ('Michal Říha', 'joke@centrum.cz');
--INSERT INTO users (username, email) VALUES ('Míloslav Sáňka', 'miloslav.sanka@gmail.com');
--INSERT INTO users (username, email) VALUES ('Miroslav Geršl', 'miroslav.gersl@medistczech.cz');
--INSERT INTO users (username, email) VALUES ('Miroslav Hulewicz', 'mira.hulewicz@centrum.cz');
--INSERT INTO users (username, email) VALUES ('Oldřich Janda', 'oldrich.janda@ojc.cz');
--INSERT INTO users (username, email) VALUES ('Pavel Havlát', 'pavel.havlat@seznam.cz');
--INSERT INTO users (username, email) VALUES ('Petr Starý', '782732@gmail.com');
--INSERT INTO users (username, email) VALUES ('Radomír Švihel', 'svihel@gmail.com');
--INSERT INTO users (username, email) VALUES ('Tereza Weinerová', 'terka.babolat@gmail.com');
--INSERT INTO users (username, email) VALUES ('Tomáš Klecer', 'jiriklecer@gmail.com');
--INSERT INTO users (username, email) VALUES ('Tomáš Lednický', 'lednicky.t@gmail.com');
--INSERT INTO users (username, email) VALUES ('Tomáš Procházka', 'ebeli@seznam.cz');
--INSERT INTO users (username, email) VALUES ('Tomáš Šplíchal', 'splichalt@seznam.cz');
--INSERT INTO users (username, email) VALUES ('Veronika Sárová', 'autosara@seznam.cz');
--INSERT INTO users (username, email) VALUES ('Vít Strádal', 'v.stradal@gmail.com');
--INSERT INTO users (username, email) VALUES ('Vojtěch Čupa', 'maracupa@gmail.com');
--INSERT INTO users (username, email) VALUES ('Zdeněk Pezlar', 'zdenek.pezlar@gmail.com');
--INSERT INTO users (username, email) VALUES ('Zdeněk Sára', 'autosara@seznam.cz');

INSERT INTO events (title, starts) VALUES ('Neděle, volná hra',          '2018-04-29 19:00:00');
INSERT INTO events (title, starts) VALUES ('Pondělí, řízený trénink',    '2018-04-30 19:00:00');
INSERT INTO events (title, starts, restriction) VALUES ('Středa, Vojta', '2018-05-02 07:30:00', '1,2,3');
INSERT INTO events (title, starts) VALUES ('Čtvrtek, volná hra',         '2018-05-03 19:00:00');

INSERT INTO presence (eventid, userid) VALUES (1, 1);
INSERT INTO presence (eventid, name)   VALUES (1, 'Lee Chong Wei');
INSERT INTO presence (eventid, userid) VALUES (1, 2);
INSERT INTO presence (eventid, userid) VALUES (1, 3);
INSERT INTO presence (eventid, userid) VALUES (1, 4);
INSERT INTO presence (eventid, userid) VALUES (2, 2);
INSERT INTO presence (eventid, userid) VALUES (2, 3);
INSERT INTO presence (eventid, userid) VALUES (3, 1);
INSERT INTO presence (eventid, userid) VALUES (3, 2);
INSERT INTO presence (eventid, userid) VALUES (3, 3);
INSERT INTO presence (eventid, userid) VALUES (3, 4);
INSERT INTO presence (eventid, userid) VALUES (4, 1);

INSERT INTO comments (eventid, userid, text) VALUES (1, 2, 'Sorry, bolí mě noha, nejdu');
INSERT INTO comments (eventid, userid, text) VALUES (1, 3, 'Zapomněl jsem.');
INSERT INTO comments (eventid, userid, text) VALUES (2, 2, 'Sorry, bolí mě noha, nejdu');
INSERT INTO comments (eventid, userid, text) VALUES (3, 2, 'Sorry, bolí mě noha, nejdu');
INSERT INTO comments (eventid, userid, text) VALUES (3, 3, 'Zaspal jsem!');
INSERT INTO comments (eventid, userid, text) VALUES (3, 4, 'Beru nové míče na odzkoušení!');
